### ISSUE TITLE
If Cs admin update the self study Organization then "Account Owner" heading  should not be displayed.

### ISSUE THREAD

**Issue by jainsmriti** [subrata1106/TestRel18#1]
If Cs admin update the self study Organization then "Account Owner" heading  should not be displayed.
![1](https://cloud.githubusercontent.com/assets/12691744/11991759/1406eec6-aa44-11e5-8ac9-4f3f4a22edc0.png)

**Comment by VrandaNagar** [comment]
fixed

**Comment by rahul-kumar11** [comment]
retested and passed
