### ISSUE TITLE
Please make changes as marked in images.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#102]
Please make changes as marked in images.
![53](https://cloud.githubusercontent.com/assets/7794513/12412548/0769a38a-be4d-11e5-9758-2f353bbab883.png)

**Comment by dharamveerSanodiya** [comment]
Changes incorporated as per the suggestion. Please validate.
Cause: UI changes

**Comment by rahul-kumar11** [comment]
retested and passed
