### ISSUE TITLE
No course is displayed on the manage user screen.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#109]
Step to reproduce:-1
1- Student in class in which a course exits and licence for this course is already expired.
2- Remove the student from class.
3- Now create a class with same course.
4- Add user in the newly created class by "Add User" or "add user to class" functionality.
5- No course will be displayed

**Comment by besiddharth** [comment]
Fixed.
Inherited Defect

**Comment by rahul-kumar11** [comment]
retested and passed
