### ISSUE TITLE
If a user activate a course in self study then the view of the self study course on my course screen is not appropriate.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#11]
If a user activate a course in self study then the view of the self study course on my course screen is not appropriate.
![8](https://cloud.githubusercontent.com/assets/7794513/12110070/620c7f46-b3ae-11e5-8b9f-4d43a2d39c39.PNG)

**Comment by rahul-kumar11** [comment]
not working as expected.

**Comment by dharamveerSanodiya** [comment]
Please check, bug is resolved.
Cause: New UI change

**Comment by rahul-kumar11** [comment]
retested and passed
