### ISSUE TITLE
On "Edit organization" details page error message is not displayed properly. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#12]
On "Edit organization" details page error message is not displayed properly. 
![9](https://cloud.githubusercontent.com/assets/7794513/12112351/0c24efb4-b3c2-11e5-8e5d-5789c46f1583.png)

**Comment by VrandaNagar** [comment]
fixed

**Comment by rahul-kumar11** [comment]
retested and passed
