### ISSUE TITLE
User is getting 12 hours difference in time on "distribute summary "page.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#120]
User is getting 12 hours difference in time on "distribute summary "page.

![image](https://cloud.githubusercontent.com/assets/7794513/12483381/cb9ba4dc-c065-11e5-9583-b62cbd2c6ef3.png)

**Comment by jainsmriti** [comment]
Fixed : Inadequate Checklist

**Comment by rahul-kumar11** [comment]
retested and passed
