### ISSUE TITLE
Please Change the "Text" on my course screen, edit class displayed during course creation. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#13]
Please Change the "Text" on my course screen, edit class displayed during course creation.

**Comment by dharamveerSanodiya** [comment]
-Updated as per the description. Now its working like charm.
Please check and let me know in case of further modification.

Cause: inadequate checklist
Regards,
Dharamveer

**Comment by rahul-kumar11** [comment]
retested and passed
