### ISSUE TITLE
On "edit class" screen during course creation status" In progress", "edit" and "delete" link should be visible.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#14]
On "edit class" screen during course creation status" In progress", "edit" and "delete" link should be visible.
![10](https://cloud.githubusercontent.com/assets/7794513/12113280/bcf0bb02-b3c7-11e5-8151-7b124cd841f9.PNG)

**Comment by dharamveerSanodiya** [comment]
-New design is applied by Vranda and Ankit.
Now it is coming as wxpected, please check.
Cause: Inherited defect
Regards,
Dharamveer

**Comment by rahul-kumar11** [comment]
retested and passed
