### ISSUE TITLE
On Course search screen the courses can be searched  for an organization when Cs admin set the organization in  context. But user is able to search the course for every org without setting the org in the context.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#15]
On Course search screen the courses can be searched  for an organization when Cs admin set the organization in  context. But user is able to search the course for every org without setting the org in the context.

**Comment by dharamveerSanodiya** [comment]
-Implemented as per the suggestion. Good job rahul.
Cause: inadequate checklist
Regards,
Dharamveer

**Comment by rahul-kumar11** [comment]
retested and passed
