### ISSUE TITLE
If user type 3 or more character in course name text box, user should get suggestion for courses.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#16]
If user type 3 or more character in course name text box, user should get suggestion for courses.

**Comment by dharamveerSanodiya** [comment]
-Implemented as per the suggestion.
Please check and let me know if further modification is required.
Cause: inadequate checklist

Regards,
Dharamveer

**Comment by rahul-kumar11** [comment]
retested and passed
