### ISSUE TITLE
"CourseSearchResult" page is not according to design doc. Please see the attached image.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#17]
"CourseSearchResult" page is not according to design doc. Please see the attached image.
![11](https://cloud.githubusercontent.com/assets/7794513/12115888/b1a62480-b3db-11e5-983e-ccc7bf3b088c.png)

**Comment by dharamveerSanodiya** [comment]
-Suggestion implemented, Please check 
Cause: inadequate checklist
Regards,
Dharamveer

**Comment by rahul-kumar11** [comment]
Horizontal line is not displayed.

**Comment by dharamveerSanodiya** [comment]
line is being included. Please check.

**Comment by rahul-kumar11** [comment]
Horizontal line should not be full.

**Comment by dharamveerSanodiya** [comment]
Please validate again

**Comment by rahul-kumar11** [comment]
retested and passed
