### ISSUE TITLE
"Manage course" pop up  is not according to design doc. Please see the attached image

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#18]
"Manage course" pop up  is not according to design doc. Please see the attached image
![13](https://cloud.githubusercontent.com/assets/7794513/12116648/5f39d7f4-b3e1-11e5-8e1f-f805fcda7422.png)

**Comment by dharamveerSanodiya** [comment]
-UI changes done as per the mentioned description.
Please check and let me know, Do we need to give there progress bar in case of success?
Cause: inadequate checklist
Regards,
Dharamveer

**Comment by rahul-kumar11** [comment]
retested and passed
