### ISSUE TITLE
User's time and date format is not implemented on the following screen: "View transfer history", "Transfer summery" & "Revoke licences summary"

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#19]
User's time and date format is not implemented on the following screen: "View transfer history", "Transfer summery" & "Revoke licences summary"
![14](https://cloud.githubusercontent.com/assets/7794513/12117062/1a558f68-b3e4-11e5-9cf6-bc560bb5fe9e.png)

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
