### ISSUE TITLE
"Undefined" error message is displayed under the "Address" text area on "Edit organization details" page.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#2]
Step to reproduce:
1- Go to Edit organization details page
2- Organization type select box should be "Please select" value in it if not then do it "please select".
3- Click on "save".
4- Click in "Address" text area and press enter.
![2](https://cloud.githubusercontent.com/assets/7794513/12047940/b0600f50-aef9-11e5-93d9-7367ce8874d5.png)

**Comment by VrandaNagar** [comment]
fixed

**Comment by rahul-kumar11** [comment]
"Cursor" size is increasing while user press enter in text area

**Comment by rahul-kumar11** [comment]
retested and passed
