### ISSUE TITLE
User's time and date format is not implemented for "Licence" related business activity.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#20]
User's time and date format is not implemented for "Licence" related business activity.
![15](https://cloud.githubusercontent.com/assets/7794513/12117239/7f18cfae-b3e5-11e5-9fbf-b1cd52de08ef.PNG)

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
