### ISSUE TITLE
Please update the text in the marked image on "edit organization" details page.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#22]
Please update the text in the marked image on "edit organization" details page.
![16](https://cloud.githubusercontent.com/assets/7794513/12142900/c8a04fdc-b4a1-11e5-97ac-cd6f6abcd5cd.png)

**Comment by VrandaNagar** [comment]
Changes have been implemented.
Please verify

**Comment by rahul-kumar11** [comment]
retested and passed
