### ISSUE TITLE
The word "code" marked in image should be "codes" on "distribute administrator joining code".

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#25]
The word "code" marked in image should be "codes" on "distribute administrator joining code".
![18](https://cloud.githubusercontent.com/assets/7794513/12163855/fade8b36-b536-11e5-8333-4a17b53aef15.PNG)

**Comment by VrandaNagar** [comment]
Resource file change.Fixed

**Comment by rahul-kumar11** [comment]
retested and fixed
