### ISSUE TITLE
"Refresh organization joining codes" should not have cross icon on right upper corner. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#26]
"Refresh organization joining codes" should not have cross icon on right upper corner. 

![19](https://cloud.githubusercontent.com/assets/7794513/12164141/50050084-b539-11e5-933a-7ab4211cb88e.PNG)

**Comment by VrandaNagar** [comment]
fixed

**Comment by rahul-kumar11** [comment]
retested and passed
