### ISSUE TITLE
"Add licence "page is not according to design doc. Please change/add text  marked in image. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#28]
"Add licence "page is not according to design doc. Please change/add text  marked in image. 
![20](https://cloud.githubusercontent.com/assets/7794513/12165614/5ba0c84a-b545-11e5-9fd8-4ae7f63464d2.png)

**Comment by VrandaNagar** [comment]
ui change.Fixed

**Comment by rahul-kumar11** [comment]
retested and passed
