### ISSUE TITLE
Some times error message text is displayed with out any CSS on "add licence" page.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#29]
Some times error message text is displayed with out any CSS on "add licence" page.
![21](https://cloud.githubusercontent.com/assets/7794513/12165643/9812512c-b545-11e5-85c0-2ae36b91a17c.PNG)

**Comment by VrandaNagar** [comment]
Cause :Inadequate checklist.
JavaScript error,please verify

**Comment by rahul-kumar11** [comment]
retested and passed
