### ISSUE TITLE
User should not able to add zero (0) licence. Is it a requirement? He also can transfer and revoke "0" licences.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#30]
User should not able to add zero (0) licence. Is it a requirement?

**Comment by rahul-kumar11** [comment]
As discussed with @NitinLeuva  this is a bug. Please resolve .

**Comment by VrandaNagar** [comment]
fixed,please verify

**Comment by VrandaNagar** [comment]
Please verify the java script change

**Comment by rahul-kumar11** [comment]
retested and passed
