### ISSUE TITLE
Please change the marked text in image on "licence for product by class" by Cs admin.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#32]
Please change the marked text in image on "licence for product by class" by Cs admin.
![22](https://cloud.githubusercontent.com/assets/7794513/12167543/cf59a47a-b552-11e5-9274-b01c5432ab30.png)

**Comment by VrandaNagar** [comment]
fixed

**Comment by rahul-kumar11** [comment]
retested and passed
