### ISSUE TITLE
Please make changes as marked in image on "Invite other org" page.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#34]
Please make changes as marked in image on "Invite other org" page.
![23](https://cloud.githubusercontent.com/assets/7794513/12168930/756b3b28-b55b-11e5-8afa-2ae3d5ca34d5.png)

**Comment by VrandaNagar** [comment]
Please verify.
Cause inadequate checklist

**Comment by rahul-kumar11** [comment]
retested and passed
