### ISSUE TITLE
If user invite another org to join the chain his chain successfully. The other org gets the "Accept" & "Reject option" for the invite. if user click on "accept" or "reject" he should get the confirmation pop for  the acceptance or rejection.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#35]
If user invite another org to join the chain his chain successfully. The other org gets the "Accept" & "Reject option" for the invite. if user click on "accept" or "reject" he should get the confirmation pop for  the acceptance or rejection.

**Comment by besiddharth** [comment]
Done. Please verify.
Cause : Inadequate Self-Review

**Comment by rahul-kumar11** [comment]
retested and passed
