### ISSUE TITLE
If a user join a Org as member of another org , user get the entry in "membership table with remove link. "remove" link is not working.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#36]
If a user join a Org as member of another org , user get the entry in "membership table with remove link. "remove" link is not working.
![24](https://cloud.githubusercontent.com/assets/7794513/12170198/25d58fe6-b565-11e5-87d8-4f5bc1fdedb7.PNG)

**Comment by besiddharth** [comment]
Done.
Cause: Inadequate Self-Review

**Comment by rahul-kumar11** [comment]
retested and passed
