### ISSUE TITLE
"Business activities" of class is not getting posted and displayed.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#38]
"Business activities" of class is not getting posted and displayed. @NitinLeuva

**Comment by NitinLeuva** [comment]
Done, this was due to usage of ASYNC call for posting the class activities in SOLR BL, checked in the code..Dharam please change the remaining calls as discussed

**Comment by dharamveerSanodiya** [comment]
Change is remaining call is done. Now activity is posting as expected. Please check.
Cause: Profile store was null in async call

**Comment by rahul-kumar11** [comment]
retested and passed
