### ISSUE TITLE
The error messages is not displayed properly on "transfer licence" page.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#39]
The error messages is not displayed properly on "transfer licence" page.
![25](https://cloud.githubusercontent.com/assets/7794513/12192653/9e1fb58e-b606-11e5-9a42-0bc709341af9.png)

**Comment by rahul-kumar11** [comment]
![image](https://cloud.githubusercontent.com/assets/7794513/12195051/92e30f90-b61a-11e5-91f2-e716cdb60b98.png)

**Comment by VrandaNagar** [comment]
Changes done as suggested.
Please verify

**Comment by rahul-kumar11** [comment]
retested and passed
