### ISSUE TITLE
If Org Admin try to add a "Org defined field" of "Drop down list" type then after clicking on "Create" Org admin gets the old UI.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#4]
Step To reproduce:-1

1-Login as Org admin
2-Go to manage org
3-Click on " Set up additional fields to help you manage your users"
4-Fill the field name and select field type as "Dope down list" and click on create

**Comment by VrandaNagar** [comment]
fixed

**Comment by rahul-kumar11** [comment]
retested and passed
