### ISSUE TITLE
user is getting "0" licence to revoke on "revoke licence" screen  although user has licence to revoke.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#43]
Step to reproduce:-
1) user has transferred licence more then on organization (Ex:-2 org and each org has 2 licences for a course) 
2- Revoke all the licences from 1 org displayed on transferred licences screen.
3- Now try to revoke licence from other org.

**Comment by rahul-kumar11** [comment]
![28](https://cloud.githubusercontent.com/assets/7794513/12197388/aa08608c-b62c-11e5-8fff-27d80dc2c1d7.png)

**Comment by besiddharth** [comment]
Please check

**Comment by rahul-kumar11** [comment]
retested and passed
