### ISSUE TITLE
Please make changes as marked in image on "Revoke licence confirmation " page.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#45]
![26](https://cloud.githubusercontent.com/assets/7794513/12198712/8476c168-b638-11e5-9009-bd2fc3ec274f.png)
Please make changes as marked in image on "Revoke licence confirmation " page.

**Comment by VrandaNagar** [comment]
Changes made as per suggestion.
Please verify

**Comment by rahul-kumar11** [comment]
retested and passed
