### ISSUE TITLE
Please make changes as marked in image on "Chain management confirmation " page.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#47]
Please make changes as marked in image on "Chain management confirmation " page.
![31](https://cloud.githubusercontent.com/assets/7794513/12198950/56bf13e0-b63a-11e5-908b-193ccfd14218.png)

**Comment by besiddharth** [comment]
This has been fixed along with previous code change.

Please test.

**Comment by rahul-kumar11** [comment]
retested and passed
