### ISSUE TITLE
On "Request to join organization" page on entering "Any numeric value"  the system return the error message "This is your own Organization ID. Please enter the Organization ID for the organization you would like to join." is not valid

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#48]
1-   User entered any value that is not any org id-Error message "Please enter a valid Organization ID."
2-  user enters "153" error message  "Please enter a valid Organization ID.".
3-  Users enters own org id then error message "This is your own Organization ID. Please enter the Organization ID for the organization you would like to join."

**Comment by rahul-kumar11** [comment]
Same will apply on  "Invite other organization " screen.

**Comment by besiddharth** [comment]
Done. Please verify.

Cause: Inherited Defect

**Comment by rahul-kumar11** [comment]
retested and passed
