### ISSUE TITLE
user is able to create "Additional fields for your chain" with out field name if user put a space in "field name" and click on create.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#49]
user is able to create "Additional fields for your chain" with out field name if user put a space in "field name" and click on create.

**Comment by VrandaNagar** [comment]
Changes incorporated as per suggestion.
Please verify

**Comment by rahul-kumar11** [comment]
after entering space the error message is not displayed.

![image](https://cloud.githubusercontent.com/assets/7794513/12453219/8bb789d6-bf92-11e5-8764-5acf2fd125f5.png)

**Comment by VrandaNagar** [comment]
Please verify.

**Comment by rahul-kumar11** [comment]
retested and passed
