### ISSUE TITLE
On "Additional fields for your chain" screen the date is displayed is not according to user's date format.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#50]
On "Additional fields for your chain" screen the date is displayed is not according to user's date format.
![34](https://cloud.githubusercontent.com/assets/7794513/12215293/f0767522-b6db-11e5-9474-059b4421807c.png)

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
