### ISSUE TITLE
If user add a filed for his child org and set some default value or set a number field and now the user try to edit the field then "default value" should be filled on "Add/edit an additional field for your chain" screen. in case of number field the "minimum ans maximum " should be filled with values.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#51]
If user add a filed for his child org and set some default value or set a number field and now the user try to edit the field then "default value" should be filled on "Add/edit an additional field for your chain" screen. In case of number field the "minimum ans maximum " should be filled with values.

**Comment by VrandaNagar** [comment]
Inadequate checklist.
Fixed,please verify

**Comment by rahul-kumar11** [comment]
retested and passed
