### ISSUE TITLE
Please make changes as marked in image on "Add/edit an additional field for your chain" page.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#52]
Please make changes as marked in image on "Add/edit an additional field for your chain" page.
![33](https://cloud.githubusercontent.com/assets/7794513/12215436/6a8c83d2-b6e2-11e5-9f15-1585fd30144e.png)
![35](https://cloud.githubusercontent.com/assets/7794513/12215438/6e34a316-b6e2-11e5-96bd-0b65f452c1e8.png)

**Comment by VrandaNagar** [comment]
Changes incorporated.
Cause:Inadequate checklist,please verify

**Comment by rahul-kumar11** [comment]
there 
![image](https://cloud.githubusercontent.com/assets/7794513/12477379/778b9dec-c02f-11e5-88aa-bd6ea726b745.png)

**Comment by VrandaNagar** [comment]
update

**Comment by rahul-kumar11** [comment]
![image](https://cloud.githubusercontent.com/assets/7794513/12482911/46e079ae-c063-11e5-9404-7b1bbade9e23.png)

**Comment by rahul-kumar11** [comment]
![image](https://cloud.githubusercontent.com/assets/7794513/12483061/fb92a2aa-c063-11e5-9ec4-f413e7096749.png)

**Comment by dharamveerSanodiya** [comment]
As suggested done, please validate.

**Comment by rahul-kumar11** [comment]
retested and passed
