### ISSUE TITLE
Please make changes as marked in image on "Additional fields for your chain" page

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#53]
![32](https://cloud.githubusercontent.com/assets/7794513/12215442/8cf53f40-b6e2-11e5-9411-42b9938afa35.png)
![36](https://cloud.githubusercontent.com/assets/7794513/12215447/c2271d6e-b6e2-11e5-9bdc-bf78ba089cd7.png)

**Comment by VrandaNagar** [comment]
Inadequate checklist.
Fixed,please verify

**Comment by rahul-kumar11** [comment]
retested and passed
