### ISSUE TITLE
User is not able to back again on "Update chain management details" until logout from the system. If user try to edit the "field defined for chain member".

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#54]
User is not able to back again on "Update chain management details" until logout from the system. If user try to edit the "field defined for chain member".

**Comment by dharamveerSanodiya** [comment]
Bug resolved as discussed.
Cause: Existiing bug

**Comment by rahul-kumar11** [comment]
retested and passed
