### ISSUE TITLE
"Date format" and validation is not working properly on "edit members field" page.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#55]
"Date format" and validation is not working properly on "edit members field" page.
![image](https://cloud.githubusercontent.com/assets/7794513/12215598/41490470-b6ea-11e5-99d1-703e1ed79662.png)

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
