### ISSUE TITLE
If user try to create an additional field with name "name", "username", "role" user get the old UI pop up.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#58]
If user try to create an additional field with name "name", "username", "role" user get the old UI pop up.
![39](https://cloud.githubusercontent.com/assets/7794513/12228279/f8a97bac-b85e-11e5-83ff-a09903900298.PNG)

**Comment by VrandaNagar** [comment]
ui bug.
Fixed

**Comment by rahul-kumar11** [comment]
![image](https://cloud.githubusercontent.com/assets/7794513/12424036/db6224b8-bf2a-11e5-8b18-c4277957caae.png)

**Comment by VrandaNagar** [comment]
Changes incorporated,please verify

**Comment by rahul-kumar11** [comment]
retested and passed
