### ISSUE TITLE
User is not able to complete the partial registration if there exits a date type org defined filed.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#59]
User is not able to complete the partial registration if there exits a date type user Org defined filed.
![40](https://cloud.githubusercontent.com/assets/7794513/12228843/ade0c064-b866-11e5-8739-f25a4b9e37d5.PNG)

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
