### ISSUE TITLE
If a user enter the valid access code in "Access code:" text box on "Access features" screen and click on " Access" user will be redirected to "Course added" screen. This screen heading should be "Access features" instead of "Course Added". 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#6]
![3](https://cloud.githubusercontent.com/assets/7794513/12087946/33c89ff4-b2fd-11e5-8f43-96e33bd48d1f.PNG)
If a user enter the valid access code in "Access code:" text box on "Access features" screen and click on " Access" user will be redirected to "Course added" screen. This screen heading should be "Access features" instead of "Course Added".

**Comment by rahul-kumar11** [comment]
interchange the colours also.

**Comment by VrandaNagar** [comment]
changes applied
Please verify

**Comment by rahul-kumar11** [comment]
retested and passed
