### ISSUE TITLE
User is getting exception, if user click on "My info" link. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#60]
User is getting exception, if user click on "My info" link. User is Org created user and user has an optional Org defined field.
![41](https://cloud.githubusercontent.com/assets/7794513/12230156/4db1d698-b874-11e5-9fd7-825577968c56.PNG)

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
