### ISSUE TITLE
If a user's language is Arabic, and calendar format is Gregorian, User sees all dates according to Hijri calendar. All dates should be displayed according to "Gregorian" calendar. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#62]
If a user's language is Arabic, and calendar format is Gregorian, User sees all dates according to Hijri calendar. All dates should be displayed according to "Gregorian" calendar.

**Comment by jainsmriti** [comment]
Fixed : Inadequate checklist.

**Comment by rahul-kumar11** [comment]
retested and passed
