### ISSUE TITLE
If a user exits in EAC not in enrolment, now login in enrolment and completed the partial registration. If EAC locale does not exits in enrolment then Enrolment set the default locale for the user.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#64]
If a user exits in EAC not in enrolment, now login in enrolment and completed the partial registration. If EAC locale does not exits in enrolment then Enrolment set the default locale for the user.

**Comment by NitinLeuva** [comment]
Not able to reproduced

**Comment by rahul-kumar11** [comment]
retested and passed
