### ISSUE TITLE
If a user is in exits in "LMSLocalizationSettingPendingUsers" and the column  "IsLocalizationSettingUpdatedInLMS" value is false then user get the "update your setting" pop up although account setting is updated in lms.  User should get this pop up when "account setting" in LMS is not updated due to any reason.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#65]
If a user is in exits in "LMSLocalizationSettingPendingUsers" and the column  "IsLocalizationSettingUpdatedInLMS" value is false then user get the "update your setting" pop up although account setting is updated in lms.  User should get this pop up when "account setting" in LMS is not updated due to any reason.

@besiddharth

**Comment by ankit-sanghvi** [comment]
updated

**Comment by rahul-kumar11** [comment]
retested and passed
