### ISSUE TITLE
User is getting two different current dates while selecting "Hijri" calendar format.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#67]
![42](https://cloud.githubusercontent.com/assets/7794513/12257948/c194a7d6-b930-11e5-8036-1b5bb56ecede.png)
User is getting two different current dates while selecting "Hijri" calendar format.

**Comment by besiddharth** [comment]
Done. Please check.

Cause : Inadequate Self-Review

**Comment by rahul-kumar11** [comment]
retested and passed
