### ISSUE TITLE
Time and date format is not according to user's date and time format on edit user details page by CS admin.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#68]
Time and date format is not according to user's date and time format on edit user details page by CS admin.
![43](https://cloud.githubusercontent.com/assets/7794513/12257943/b2393554-b930-11e5-9a56-b5eac88bbdc6.PNG)

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
