### ISSUE TITLE
Change the text and colour marked in image on "Upload logo" screen.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#7]
Change the text and colour marked in image on "Upload logo" screen.
![4](https://cloud.githubusercontent.com/assets/7794513/12087966/5d820916-b2fd-11e5-848f-6c9ca08e2b90.png)

**Comment by VrandaNagar** [comment]
fixed

**Comment by VrandaNagar** [comment]
Please verify the changes
Cause:Inadequate checklist

**Comment by rahul-kumar11** [comment]
retested and passed
