### ISSUE TITLE
The error message "Please select at least one user." is not valid, if Lms admin try to remove any outage without selecting any outage.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#77]
The error message "Please select at least one user." is not valid, if Lms admin try to remove any outage without selecting any outage.
![image](https://cloud.githubusercontent.com/assets/7794513/12267985/acb65646-b9af-11e5-913f-07b581426112.png)

**Comment by dharamveerSanodiya** [comment]
Message is change as per the suggestion 
New message is - Please select at least one outage.
Cause: inadequate checklist

**Comment by rahul-kumar11** [comment]
retested and passed
