### ISSUE TITLE
User is not able "search courses" in self study organization.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#78]
User is not able "search courses" in self study organization.

**Comment by dharamveerSanodiya** [comment]
Start date is not getting set while creating self study course.
If date range is given in the search then it will filter out as per the given criteria.
Do we need to change this?
@NitinLeuva

**Comment by NitinLeuva** [comment]
Should be fixed now, please check.

Nitin

**Comment by rahul-kumar11** [comment]
retested and passed
