### ISSUE TITLE
On "Add Licences" page check boxes should behave like "radio" button.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#8]
On "Add Licences" page check boxes should behave like "radio" button.
![5](https://cloud.githubusercontent.com/assets/7794513/12088133/a45db2f8-b2fe-11e5-80aa-870ee6b8fc84.png)

**Comment by VrandaNagar** [comment]
fixed

**Comment by rahul-kumar11** [comment]
retested and passed
