### ISSUE TITLE
On course search screen if user enters the "course name "in text box then system should return the specific course only. System should not follow the partial search logic.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#80]
On course search screen if user enters the "course name "in text box then system should return the specific course only. System should not follow the partial search logic.

**Comment by dharamveerSanodiya** [comment]
-Partial seach logic is being changed as per the description.
Cause : inadequate checklist

**Comment by rahul-kumar11** [comment]
retested and passed
