### ISSUE TITLE
Please make changes on "edit class screen" as marked in images.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#83]
Please make changes on "edit class screen" as marked in images.
![46](https://cloud.githubusercontent.com/assets/7794513/12353436/1e75d036-bbf4-11e5-903e-7786e80901e7.png)

**Comment by dharamveerSanodiya** [comment]
fixed the design issue

**Comment by rahul-kumar11** [comment]
retested and passed
