### ISSUE TITLE
If CS try to update a user and enter the " Invalid Email"  and click on "Update"  user gets "global" server side error message. User should get "client side" error message "Please enter valid email address".

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#84]
If CS try to update a user and enter the " Invalid Email"  and click on "Update"  user gets "global" server side error message. User should get "client side" error message "Please enter valid email address".

**Comment by dharamveerSanodiya** [comment]
Resolved as per the suggestion.
Please validate

**Comment by rahul-kumar11** [comment]
username should not be less then 5 character

**Comment by dharamveerSanodiya** [comment]
Username min lenght constraint is added as suggestion.
Good job rahul :+1: 
Cause: Existing bug :

**Comment by rahul-kumar11** [comment]
retested and passed
