### ISSUE TITLE
User is getting exception after clicking on "Business activity" link if user's calendar format is "Hijri".

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#87]
User is getting exception after clicking on "Business activity" link if user's calendar format is "Hijri".
![image](https://cloud.githubusercontent.com/assets/7794513/12385429/7d11cfe4-bd68-11e5-9438-07d158c50db1.png)

**Comment by jainsmriti** [comment]
Fixed : Inadequate checklist.

**Comment by rahul-kumar11** [comment]
retested and passed
