### ISSUE TITLE
Please make changes as marked in image on "Edit User" by CS admin page..

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#88]
Please make changes as marked in image on "Edit User" by CS admin page..
![44](https://cloud.githubusercontent.com/assets/7794513/12385714/5698539e-bd6b-11e5-9053-abfd4d166795.png)

**Comment by dharamveerSanodiya** [comment]
Bug is resolved, please check.
Cause: Inadequate checklist

**Comment by rahul-kumar11** [comment]
retested and passed
