### ISSUE TITLE
If user is "self register user" and the Cs admin try to edit the user, User's role text box looks like read-only, although Cs admin can change the role. The role text box should not looked like read only.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#89]
If user is "self register user" and the Cs admin try to edit the user, User's role text box looks like read-only, although Cs admin can change the role. The role text box should not looked like read only.

**Comment by dharamveerSanodiya** [comment]
Bug is resolved. Please check.
Cause: UI change

**Comment by rahul-kumar11** [comment]
CS admin is not able to change the role of the self study user

**Comment by dharamveerSanodiya** [comment]
Upadated as per the suggestion. Please validate
Cause: Inadequate checklist

**Comment by rahul-kumar11** [comment]
retested and passed
