### ISSUE TITLE
if there is a org defined field of date type exits in org and Org admin edit a student user then the "date" in the field displayed is not according to the org admin date format.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#9]
if there is a org defined field of date type exits in org and Org admin edit a student user then the "date" in the field displayed is not according to the org admin date format.

![6](https://cloud.githubusercontent.com/assets/7794513/12088309/f8edfa98-b2ff-11e5-8594-835fdffed987.png)

**Comment by jainsmriti** [comment]
Fixed.

**Comment by rahul-kumar11** [comment]
retested and passed
