### ISSUE TITLE
Please make changes as marked in image on  "Join Class" , "access content" and accesslink pages from "Edit User" by CS admin page.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#91]
Please make changes as marked in image on "Edit User" by CS admin page.
![47](https://cloud.githubusercontent.com/assets/7794513/12387709/f73d1f50-bd7a-11e5-94dc-5323c122b1e0.png)

**Comment by dharamveerSanodiya** [comment]
UI changes are done as per the suggestion.
Please check.
Cause: UI changes

**Comment by rahul-kumar11** [comment]
retested and passed
