### ISSUE TITLE
Please make changes as marked in image on "Edit user " by CS admin page.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#92]
Please make changes as marked in image on "Edit user " by CS admin page.
![48](https://cloud.githubusercontent.com/assets/7794513/12387787/60abe9a8-bd7b-11e5-9f69-587d1219282d.png)

**Comment by dharamveerSanodiya** [comment]
changes done as per the suggestion.
Cause: Suggestion

**Comment by rahul-kumar11** [comment]
The message should be displayed in boxes

**Comment by dharamveerSanodiya** [comment]
Message is enclosed with the boxes. Please validate.
Cause: Suggestion

**Comment by rahul-kumar11** [comment]
retested and passed
