### ISSUE TITLE
The page is getting refreshed if user click on "Cancel" button on pop up "edit user" from CS admin. The page should not refresh is user returns on the same page.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#93]
The page is getting refreshed if user click on "Cancel" button on pop up "edit user" from CS admin. The page should not refresh is user returns on the same page.

**Comment by dharamveerSanodiya** [comment]
Bug is resolved. Please check.
Cause: UI changes

**Comment by rahul-kumar11** [comment]
retested and passed
