### ISSUE TITLE
Please make changes as marked in images on "Leave Class" and "leave Org" pop up.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#94]
Please make changes as marked in images on "Leave Class" and "leave Org" pop up.
![49](https://cloud.githubusercontent.com/assets/7794513/12388202/f1961306-bd7d-11e5-8920-e6cd52fea385.png)

**Comment by dharamveerSanodiya** [comment]
Changes done as per the suggestion.
Cause: Inadequate checklist

**Comment by rahul-kumar11** [comment]
retested and passed
