### ISSUE TITLE
If user is present in any class of an org, CS admin try to remove user from "the ORG". Cs admin does not gets any error message. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#95]
If user is present in any class of an org, CS admin try to remove user from "the ORG". Cs admin does not gets any error message.

**Comment by dharamveerSanodiya** [comment]
For success and failure message is being append as suggested.
Cause: Exiting bug.

**Comment by rahul-kumar11** [comment]
retested and passed
