### ISSUE TITLE
If Cs admin try to join a user in "Archived" or "deleted" class. CS admin does not get any message neither user join in class.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#97]
If Cs admin try to join a user in "Archived" or "deleted" class. CS admin does not get any message neither user join in class.

**Comment by dharamveerSanodiya** [comment]
Bug is resolved. Please check.
Cause: Inadequate checklist

**Comment by rahul-kumar11** [comment]
retested and passed
