### ISSUE TITLE
If Cs Add try to add a user in class, the join successful screen requires changes as marked in images.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#98]
If Cs Add try to add a user in class, the join successful screen requires changes as marked in images.
![50](https://cloud.githubusercontent.com/assets/7794513/12389995/de13b026-bd88-11e5-96f9-7defb5208a3c.png)

**Comment by rahul-kumar11** [comment]
![51](https://cloud.githubusercontent.com/assets/7794513/12412905/572dbd22-be50-11e5-8809-e46bfbac1e70.png)

**Comment by dharamveerSanodiya** [comment]
Bug is resolved. Please check.
Cause: Existing bug

**Comment by rahul-kumar11** [comment]
retested and passed
