### ISSUE TITLE
If CS admin add user in course, the course added screen has the changes as marked in images.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#99]
If CS admin add user in course, the course added screen has the changes as marked in images.
![51](https://cloud.githubusercontent.com/assets/7794513/12391053/7760b80c-bd91-11e5-996d-5fdbc559a2de.png)

**Comment by dharamveerSanodiya** [comment]
Implementation is done as per the suggestion.
Please validate.
Cause: UI change

**Comment by rahul-kumar11** [comment]
retested and passed
